name: unit_converter
description: Convert between feets and meters.
version: 1.0.0
author: Olivers De Abreu <olivers@symmetricslab.com>
homepage: https://symmetricslab.com

environment:
  sdk: ">=2.7.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
